git add DY3JetsToLL_M/*.* 
git add SingleEl_Run2012C_part1/*.* 
git add SingleEl_Run2012A_v1/*.* 
git add T_t/*.* 
git add DY1JetsToLL_M/*.* 
git add template/*.* 
git add DY2JetsToLL_M/*.* 
git add T_tW/*.* 
git add SingleEl_Run2012B/*.* 
git add SingleEl_Run2012C_part2/*.* 
git add SingleEl_Run2012D/*.* 
git add T_s/*.* 
git add TT_CT10_TuneZ2star_8TeV/*.* 
git add DY4JetsToLL_M/*.* 
git add Tbar_s/*.* 
git add Tbar_t/*.* 
git add Tbar_tW/*.* 
git add W1JetsToLNu_TuneZ2Star_8TeV/*.* 
git add W2JetsToLNu_TuneZ2Star_8TeV/*.* 
git add W3JetsToLNu_TuneZ2Star_8TeV/*.* 
git add W4JetsToLNu_TuneZ2Star_8TeV/*.* 
