cd PDF_0
source grid_sub_separated.csh
cd ..
cd PDF_1
source grid_sub_separated.csh
cd ..
cd PDF_2
source grid_sub_separated.csh
cd ..
cd PDF_3
source grid_sub_separated.csh
cd ..
cd PDF_4
source grid_sub_separated.csh
cd ..
cd PDF_5
source grid_sub_separated.csh
cd ..
cd PDF_6
source grid_sub_separated.csh
cd ..
cd PDF_7
source grid_sub_separated.csh
cd ..
cd PDF_8
source grid_sub_separated.csh
cd ..
cd PDF_9
source grid_sub_separated.csh
cd ..
cd PDF_10
source grid_sub_separated.csh
cd ..
cd PDF_11
source grid_sub_separated.csh
cd ..
cd PDF_12
source grid_sub_separated.csh
cd ..
cd PDF_13
source grid_sub_separated.csh
cd ..
cd PDF_14
source grid_sub_separated.csh
cd ..
cd PDF_15
source grid_sub_separated.csh
cd ..
cd PDF_16
source grid_sub_separated.csh
cd ..
cd PDF_17
source grid_sub_separated.csh
cd ..
cd PDF_18
source grid_sub_separated.csh
cd ..
cd PDF_19
source grid_sub_separated.csh
cd ..
cd PDF_20
source grid_sub_separated.csh
cd ..
cd PDF_21
source grid_sub_separated.csh
cd ..
cd PDF_22
source grid_sub_separated.csh
cd ..
cd PDF_23
source grid_sub_separated.csh
cd ..
cd PDF_24
source grid_sub_separated.csh
cd ..
cd PDF_25
source grid_sub_separated.csh
cd ..
cd PDF_26
source grid_sub_separated.csh
cd ..
cd PDF_27
source grid_sub_separated.csh
cd ..
cd PDF_28
source grid_sub_separated.csh
cd ..
cd PDF_29
source grid_sub_separated.csh
cd ..
cd PDF_30
source grid_sub_separated.csh
cd ..
cd PDF_31
source grid_sub_separated.csh
cd ..
cd PDF_32
source grid_sub_separated.csh
cd ..
cd PDF_33
source grid_sub_separated.csh
cd ..
cd PDF_34
source grid_sub_separated.csh
cd ..
cd PDF_35
source grid_sub_separated.csh
cd ..
cd PDF_36
source grid_sub_separated.csh
cd ..
cd PDF_37
source grid_sub_separated.csh
cd ..
cd PDF_38
source grid_sub_separated.csh
cd ..
cd PDF_39
source grid_sub_separated.csh
cd ..
cd PDF_40
source grid_sub_separated.csh
cd ..
cd PDF_41
source grid_sub_separated.csh
cd ..
cd PDF_42
source grid_sub_separated.csh
cd ..
cd PDF_43
source grid_sub_separated.csh
cd ..
cd PDF_44
source grid_sub_separated.csh
cd ..
cd PDF_45
source grid_sub_separated.csh
cd ..
cd PDF_46
source grid_sub_separated.csh
cd ..
cd PDF_47
source grid_sub_separated.csh
cd ..
cd PDF_48
source grid_sub_separated.csh
cd ..
cd PDF_49
source grid_sub_separated.csh
cd ..
cd PDF_50
source grid_sub_separated.csh
cd ..
cd PDF_51
source grid_sub_separated.csh
cd ..
cd PDF_52
source grid_sub_separated.csh
cd ..
