rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r TT_CT10_TuneZ2star_8TeV/grid_sub.csh
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r TT_CT10_TuneZ2star_8TeV/grid_sub.csh
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
rm -r T_s/grid_sub.csh
cp  template/grid_sub.csh T_s
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r TT_CT10_TuneZ2star_8TeV/grid_sub.csh
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
rm -r T_s/grid_sub.csh
cp  template/grid_sub.csh T_s
rm -r T_t/grid_sub.csh
cp  template/grid_sub.csh T_t
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r TT_CT10_TuneZ2star_8TeV/grid_sub.csh
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
rm -r T_s/grid_sub.csh
cp  template/grid_sub.csh T_s
rm -r T_t/grid_sub.csh
cp  template/grid_sub.csh T_t
rm -r T_tW/grid_sub.csh
cp  template/grid_sub.csh T_tW
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r TT_CT10_TuneZ2star_8TeV/grid_sub.csh
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
rm -r T_s/grid_sub.csh
cp  template/grid_sub.csh T_s
rm -r T_t/grid_sub.csh
cp  template/grid_sub.csh T_t
rm -r T_tW/grid_sub.csh
cp  template/grid_sub.csh T_tW
rm -r Tbar_s/grid_sub.csh
cp  template/grid_sub.csh Tbar_s
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r TT_CT10_TuneZ2star_8TeV/grid_sub.csh
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
rm -r T_s/grid_sub.csh
cp  template/grid_sub.csh T_s
rm -r T_t/grid_sub.csh
cp  template/grid_sub.csh T_t
rm -r T_tW/grid_sub.csh
cp  template/grid_sub.csh T_tW
rm -r Tbar_s/grid_sub.csh
cp  template/grid_sub.csh Tbar_s
rm -r Tbar_t/grid_sub.csh
cp  template/grid_sub.csh Tbar_t
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r TT_CT10_TuneZ2star_8TeV/grid_sub.csh
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
rm -r T_s/grid_sub.csh
cp  template/grid_sub.csh T_s
rm -r T_t/grid_sub.csh
cp  template/grid_sub.csh T_t
rm -r T_tW/grid_sub.csh
cp  template/grid_sub.csh T_tW
rm -r Tbar_s/grid_sub.csh
cp  template/grid_sub.csh Tbar_s
rm -r Tbar_t/grid_sub.csh
cp  template/grid_sub.csh Tbar_t
rm -r Tbar_tW/grid_sub.csh
cp  template/grid_sub.csh Tbar_tW
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r TT_CT10_TuneZ2star_8TeV/grid_sub.csh
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
rm -r T_s/grid_sub.csh
cp  template/grid_sub.csh T_s
rm -r T_t/grid_sub.csh
cp  template/grid_sub.csh T_t
rm -r T_tW/grid_sub.csh
cp  template/grid_sub.csh T_tW
rm -r Tbar_s/grid_sub.csh
cp  template/grid_sub.csh Tbar_s
rm -r Tbar_t/grid_sub.csh
cp  template/grid_sub.csh Tbar_t
rm -r Tbar_tW/grid_sub.csh
cp  template/grid_sub.csh Tbar_tW
rm -r W1JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W1JetsToLNu_TuneZ2Star_8TeV
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r TT_CT10_TuneZ2star_8TeV/grid_sub.csh
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
rm -r T_s/grid_sub.csh
cp  template/grid_sub.csh T_s
rm -r T_t/grid_sub.csh
cp  template/grid_sub.csh T_t
rm -r T_tW/grid_sub.csh
cp  template/grid_sub.csh T_tW
rm -r Tbar_s/grid_sub.csh
cp  template/grid_sub.csh Tbar_s
rm -r Tbar_t/grid_sub.csh
cp  template/grid_sub.csh Tbar_t
rm -r Tbar_tW/grid_sub.csh
cp  template/grid_sub.csh Tbar_tW
rm -r W1JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W1JetsToLNu_TuneZ2Star_8TeV
rm -r W2JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W2JetsToLNu_TuneZ2Star_8TeV
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r TT_CT10_TuneZ2star_8TeV/grid_sub.csh
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
rm -r T_s/grid_sub.csh
cp  template/grid_sub.csh T_s
rm -r T_t/grid_sub.csh
cp  template/grid_sub.csh T_t
rm -r T_tW/grid_sub.csh
cp  template/grid_sub.csh T_tW
rm -r Tbar_s/grid_sub.csh
cp  template/grid_sub.csh Tbar_s
rm -r Tbar_t/grid_sub.csh
cp  template/grid_sub.csh Tbar_t
rm -r Tbar_tW/grid_sub.csh
cp  template/grid_sub.csh Tbar_tW
rm -r W1JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W1JetsToLNu_TuneZ2Star_8TeV
rm -r W2JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W2JetsToLNu_TuneZ2Star_8TeV
rm -r W3JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W3JetsToLNu_TuneZ2Star_8TeV
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r TT_CT10_TuneZ2star_8TeV/grid_sub.csh
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
rm -r T_s/grid_sub.csh
cp  template/grid_sub.csh T_s
rm -r T_t/grid_sub.csh
cp  template/grid_sub.csh T_t
rm -r T_tW/grid_sub.csh
cp  template/grid_sub.csh T_tW
rm -r Tbar_s/grid_sub.csh
cp  template/grid_sub.csh Tbar_s
rm -r Tbar_t/grid_sub.csh
cp  template/grid_sub.csh Tbar_t
rm -r Tbar_tW/grid_sub.csh
cp  template/grid_sub.csh Tbar_tW
rm -r W1JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W1JetsToLNu_TuneZ2Star_8TeV
rm -r W2JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W2JetsToLNu_TuneZ2Star_8TeV
rm -r W3JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W3JetsToLNu_TuneZ2Star_8TeV
rm -r W4JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W4JetsToLNu_TuneZ2Star_8TeV
rm -r DY1JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY1JetsToLL_M
rm -r DY2JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY2JetsToLL_M
rm -r DY3JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY3JetsToLL_M
rm -r DY4JetsToLL_M/grid_sub.csh
cp  template/grid_sub.csh DY4JetsToLL_M
rm -r QCD_Pt-15to3000/grid_sub.csh
cp  template/grid_sub.csh QCD_Pt-15to3000
rm -r SingleEl_Run2012A/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012A
rm -r SingleEl_Run2012B/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012B
rm -r SingleEl_Run2012C_part1/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part1
rm -r SingleEl_Run2012C_part2/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012C_part2
rm -r SingleEl_Run2012D/grid_sub.csh
cp  template/grid_sub.csh SingleEl_Run2012D
rm -r TT_CT10_TuneZ2star_8TeV/grid_sub.csh
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
rm -r T_s/grid_sub.csh
cp  template/grid_sub.csh T_s
rm -r T_t/grid_sub.csh
cp  template/grid_sub.csh T_t
rm -r T_tW/grid_sub.csh
cp  template/grid_sub.csh T_tW
rm -r Tbar_s/grid_sub.csh
cp  template/grid_sub.csh Tbar_s
rm -r Tbar_t/grid_sub.csh
cp  template/grid_sub.csh Tbar_t
rm -r Tbar_tW/grid_sub.csh
cp  template/grid_sub.csh Tbar_tW
rm -r W1JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W1JetsToLNu_TuneZ2Star_8TeV
rm -r W2JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W2JetsToLNu_TuneZ2Star_8TeV
rm -r W3JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W3JetsToLNu_TuneZ2Star_8TeV
rm -r W4JetsToLNu_TuneZ2Star_8TeV/grid_sub.csh
cp  template/grid_sub.csh W4JetsToLNu_TuneZ2Star_8TeV
