cp  template/grid_sub.csh DY1JetsToLL_M
cp  template/grid_sub.csh DY2JetsToLL_M
cp  template/grid_sub.csh DY3JetsToLL_M
cp  template/grid_sub.csh DY4JetsToLL_M
cp  template/grid_sub.csh QCD_Pt-15to3000
cp  template/grid_sub.csh SingleEl_Run2012A
cp  template/grid_sub.csh SingleEl_Run2012B
cp  template/grid_sub.csh SingleEl_Run2012C_part1
cp  template/grid_sub.csh SingleEl_Run2012C_part2
cp  template/grid_sub.csh SingleEl_Run2012D
cp  template/grid_sub.csh T_s
cp  template/grid_sub.csh T_t
cp  template/grid_sub.csh T_tW
cp  template/grid_sub.csh Tbar_s
cp  template/grid_sub.csh Tbar_t
cp  template/grid_sub.csh Tbar_tW
cp  template/grid_sub.csh template
cp  template/grid_sub.csh TT_CT10_TuneZ2star_8TeV
cp  template/grid_sub.csh W1JetsToLNu_TuneZ2Star_8TeV
cp  template/grid_sub.csh W2JetsToLNu_TuneZ2Star_8TeV
cp  template/grid_sub.csh W3JetsToLNu_TuneZ2Star_8TeV
cp  template/grid_sub.csh W4JetsToLNu_TuneZ2Star_8TeV
