python  ../stack_plotter.py --yields yes --var cos_theta_cs --weight correction_weight  --Min -1 --Max 1 --name corrected --bin 20 --dir temp_angles --xaxis "cos#theta*"
python   ../stack_plotter.py --var ttbar_mass --weight correction_weight  --Min 350 --Max 1750 --name corrected --bin 40 --dir temp_angles --xaxis "M_{tt}(GeV)"
python   ../stack_plotter.py --var "abs(Feynman_x)" --weight correction_weight  --Min 0 --Max 0.6 --name corrected --bin 30 --dir temp_angles --xaxis "|x_{F}|"
python  ../stack_plotter.py --var charge_ratio --weight correction_weight  --Min 0 --Max 6  --name corrected --bin 6 --dir temp_angles --xaxis "charge_ratio"
python   ../stack_plotter.py --var "lnL" --weight correction_weight  --Min -30 --Max 100 --name corrected --bin 40 --dir temp_angles --xaxis "kinfit -2lnL"
