git add DY1JetsToLL_M/*.py DY1JetsToLL_M/ana.* 
git add DY2JetsToLL_M/*.py DY2JetsToLL_M/ana.* 
git add DY3JetsToLL_M/*.py DY3JetsToLL_M/ana.* 
git add DY4JetsToLL_M/*.py DY4JetsToLL_M/ana.* 
git add SingleEl_Run2012A_v1/*.py SingleEl_Run2012A_v1/ana.* 
git add SingleEl_Run2012B/*.py SingleEl_Run2012B/ana.* 
git add SingleEl_Run2012C_part1/*.py SingleEl_Run2012C_part1/ana.* 
git add SingleEl_Run2012C_part2/*.py SingleEl_Run2012C_part2/ana.* 
git add SingleEl_Run2012D/*.py SingleEl_Run2012D/ana.* 
git add TT_CT10_TuneZ2star_8TeV/*.py TT_CT10_TuneZ2star_8TeV/ana.* 
git add T_s/*.py T_s/ana.* 
git add T_t/*.py T_t/ana.* 
git add T_tW/*.py T_tW/ana.* 
git add Tbar_s/*.py Tbar_s/ana.* 
git add Tbar_t/*.py Tbar_t/ana.* 
git add Tbar_tW/*.py Tbar_tW/ana.* 
git add W1JetsToLNu_TuneZ2Star_8TeV/*.py W1JetsToLNu_TuneZ2Star_8TeV/ana.* 
git add W2JetsToLNu_TuneZ2Star_8TeV/*.py W2JetsToLNu_TuneZ2Star_8TeV/ana.* 
git add W3JetsToLNu_TuneZ2Star_8TeV/*.py W3JetsToLNu_TuneZ2Star_8TeV/ana.* 
git add W4JetsToLNu_TuneZ2Star_8TeV/*.py W4JetsToLNu_TuneZ2Star_8TeV/ana.* 
git add template/*.py template/ana.* 
