mv *.log logs 
rm *.tgz  *.cmd condor-*
hadd all_reco/T_s_reco.root tmp/T_s*.root
hadd all_reco/T_t_reco.root tmp/T_t*.root
hadd all_reco/T_tW_reco.root tmp/T_tW*.root
hadd all_reco/Tbar_s_reco.root tmp/Tbar_s*.root
hadd all_reco/Tbar_t_reco.root tmp/Tbar_t*.root
hadd all_reco/Tbar_tW_reco.root tmp/Tbar_tW*.root
hadd all_reco/W1JetsToLNu_TuneZ2Star_8TeV_reco.root tmp/W1JetsToLNu_TuneZ2Star_8TeV*.root
hadd all_reco/W2JetsToLNu_TuneZ2Star_8TeV_reco.root tmp/W2JetsToLNu_TuneZ2Star_8TeV*.root
hadd all_reco/W3JetsToLNu_TuneZ2Star_8TeV_reco.root tmp/W3JetsToLNu_TuneZ2Star_8TeV*.root
hadd all_reco/W4JetsToLNu_TuneZ2Star_8TeV_reco.root tmp/W4JetsToLNu_TuneZ2Star_8TeV*.root
hadd all_reco/DY1JetsToLL_M_reco.root tmp/DY1JetsToLL_M*.root
hadd all_reco/DY2JetsToLL_M_reco.root tmp/DY2JetsToLL_M*.root
hadd all_reco/DY3JetsToLL_M_reco.root tmp/DY3JetsToLL_M*.root
hadd all_reco/DY4JetsToLL_M_reco.root tmp/DY4JetsToLL_M*.root
hadd all_reco/TT_CT10_TuneZ2star_8TeV_reco.root tmp/TT_CT10_TuneZ2star_8TeV*.root
hadd all_reco/TT_SC_CT10_TuneZ2star_8TeV_reco.root tmp/TT_SC_CT10_TuneZ2star_8TeV*.root
hadd all_reco/TT_8TeV-mcatnlo_reco.root tmp/TT_8TeV-mcatnlo*.root
hadd all_reco/SingleEl_Run2012ABCD_reco.root tmp/SingleEl_Run2012ABCD*.root
hadd all_reco/SingleMu_Run2012ABCD_reco.root tmp/SingleMu_Run2012ABCD*.root
